-- Get list of users (schema) in db

COL USERNAME FORMAT A30;
COL PROFILE FORMAT A30;

SELECT ROW_NUMBER() OVER(ORDER BY CREATED DESC) NUM,
        USERNAME,
        ACCOUNT_STATUS,
		PROFILE
FROM DBA_USERS
ORDER BY CREATED DESC;
